AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for Telemetry Lambda and API Gateway
Globals:
  Function:
    Timeout: 30
Resources:
  TelemetryProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: telemetry-processor-lambda/dist/index.handler
      Runtime: nodejs18.x
      CodeUri: s3://eon-telemetry/9c0018f116da641864900a5e3dd39e73
      Environment:
        Variables:
          AWS_REGION:
            Ref: AWS::Region
          DYNAMO_TABLE:
            Ref: TelemetryStoreTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /telemetries/{siteId}
            Method: post
    Metadata:
      SamResourceId: TelemetryProcessorFunction
  TelemetryRetrieverFunctionBySiteId:
    Type: AWS::Serverless::Function
    Properties:
      Handler: telemetry-retriever-lambda/dist/index.handler
      Runtime: nodejs18.x
      CodeUri: s3://eon-telemetry/55a2edf4b17fe06f836de3a058bd7772
      Environment:
        Variables:
          AWS_REGION:
            Ref: AWS::Region
          DYNAMO_TABLE:
            Ref: TelemetryStoreTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /telemetries/siteId/{siteId}
            Method: get
    Metadata:
      SamResourceId: TelemetryRetrieverFunctionBySiteId
  TelemetryRetrieverFunctionByDeviceId:
    Type: AWS::Serverless::Function
    Properties:
      Handler: telemetry-retriever-lambda/dist/index.handler
      Runtime: nodejs18.x
      CodeUri: s3://eon-telemetry/55a2edf4b17fe06f836de3a058bd7772
      Environment:
        Variables:
          AWS_REGION:
            Ref: AWS::Region
          DYNAMO_TABLE:
            Ref: TelemetryStoreTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /telemetries/deviceId/{deviceId}
            Method: get
    Metadata:
      SamResourceId: TelemetryRetrieverFunctionByDeviceId
  TelemetryRetrieverFunctionByTimeRange:
    Type: AWS::Serverless::Function
    Properties:
      Handler: telemetry-retriever-lambda/dist/index.handler
      Runtime: nodejs18.x
      CodeUri: s3://eon-telemetry/55a2edf4b17fe06f836de3a058bd7772
      Environment:
        Variables:
          AWS_REGION:
            Ref: AWS::Region
          DYNAMO_TABLE:
            Ref: TelemetryStoreTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /telemetries/timerange/{timeFrom}/{timeTo}
            Method: get
    Metadata:
      SamResourceId: TelemetryRetrieverFunctionByTimeRange
  TelemetryStoreTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: TelemetryStore
      AttributeDefinitions:
      - AttributeName: deviceId
        AttributeType: S
      - AttributeName: creationTime
        AttributeType: N
      KeySchema:
      - AttributeName: deviceId
        KeyType: HASH
      - AttributeName: creationTime
        KeyType: RANGE
      GlobalSecondaryIndexes:
      - IndexName: CreationTimeIndex
        KeySchema:
        - AttributeName: creationTime
          KeyType: HASH
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
      - IndexName: DeviceIdIndex
        KeySchema:
        - AttributeName: deviceId
          KeyType: HASH
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    Metadata:
      SamResourceId: TelemetryStoreTable
Outputs:
  TelemetryStoreTableName:
    Description: Telemetry Store DynamoDB Table Name
    Value:
      Ref: TelemetryStoreTable
