AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for Telemetry Processor Lambda and API Gateway
Globals:
  Function:
    Timeout: 30
Resources:
  TelemetryProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/telemetryProcessor.handler
      Runtime: nodejs18.x
      CodeUri: s3://eon-telemetry/7dcf0abbe5ffcd18ec0ffaf09e1aa5c8
      Environment:
        Variables:
          TABLE_NAME:
            Ref: TelemetryStoreTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /telemetry
            Method: post
    Metadata:
      SamResourceId: TelemetryProcessorFunction
  TelemetryStoreTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: TelemetryStore
      AttributeDefinitions:
      - AttributeName: deviceId
        AttributeType: S
      - AttributeName: creationTime
        AttributeType: N
      KeySchema:
      - AttributeName: deviceId
        KeyType: HASH
      - AttributeName: creationTime
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
    Metadata:
      SamResourceId: TelemetryStoreTable
Outputs:
  TelemetryProcessorFunctionArn:
    Description: Telemetry Processor Lambda Function ARN
    Value:
      Fn::GetAtt:
      - TelemetryProcessorFunction
      - Arn
  TelemetryStoreTableName:
    Description: Telemetry Store DynamoDB Table Name
    Value:
      Ref: TelemetryStoreTable
